package model;

import java.util.ArrayList;
import java.util.Collection;

import domainapp.basics.exceptions.ConstraintViolationException;
import domainapp.basics.model.meta.AttrRef;
import domainapp.basics.model.meta.DAssoc;
import domainapp.basics.model.meta.DAttr;
import domainapp.basics.model.meta.DOpt;
import domainapp.basics.model.meta.MetaConstants;
import domainapp.basics.model.meta.DAssoc.AssocEndType;
import domainapp.basics.model.meta.DAssoc.AssocType;
import domainapp.basics.model.meta.DAssoc.Associate;
import domainapp.basics.model.meta.DAttr.Type;
import domainapp.basics.model.meta.DClass;
import domainapp.basics.util.Tuple;

import model.Customer;

/**
 * @overview represent a country (a ForeignSeafood's origin)
 * 
 * @author Nguyen Thanh Tung
 */
@DClass(schema = "seafoodman")
public class TypeOfSeafood {
	
	// attributes
	@DAttr(name = "id", id = true, auto = true, type = Type.Integer, length = 3, mutable = false, optional = false)
	private int id;
	private static int idCounter = 0;

	@DAttr(name = "name", type = Type.String, length = 20, optional = false)
	private String name;

	@DAttr(name="seafood",type=Type.Domain,serialisable=false)
	@DAssoc(ascName="seafood-has-type",role="type",
	ascType=AssocType.One2Many, endType=AssocEndType.One,
	associate=@Associate(type=Seafood.class,cardMin=1,cardMax=MetaConstants.CARD_MORE))
	private Collection<Seafood> seafoods;

	@DOpt(type = DOpt.Type.DataSourceConstructor)
	public TypeOfSeafood(@AttrRef("id") Integer id, @AttrRef("name") String name) {
		this(id, name, null);
	}

	@DOpt(type = DOpt.Type.ObjectFormConstructor)
	public TypeOfSeafood(@AttrRef("name") String name, @AttrRef("seafood") Collection<Seafood> seafood) {
		this(null, name, seafood);
	}

	// Constructor with name only
	@DOpt(type = DOpt.Type.ObjectFormConstructor)
	@DOpt(type = DOpt.Type.RequiredConstructor)
	public TypeOfSeafood(@AttrRef("name") String name) {
		this(null, name, null);
	}

	private TypeOfSeafood(Integer id, String type, Collection<Seafood> seafood) {
		this.id = nextId(id);
		this.name = type;
		seafoods = new ArrayList<>();
	}

	private static int nextId(Integer currID) {
		if (currID == null) {
			idCounter++;
			return idCounter;
		} else {
			int num = currID.intValue();
			if (num > idCounter)
				idCounter = num;

			return currID;
		}
	}

	/**
	 * @requires minVal != null /\ maxVal != null
	 * @effects update the auto-generated value of attribute <tt>attrib</tt>,
	 *          specified for <tt>derivingValue</tt>, using <tt>minVal, maxVal</tt>
	 */
	@DOpt(type = DOpt.Type.AutoAttributeValueSynchroniser)
	public static void updateAutoGeneratedValue(DAttr attrib, Tuple derivingValue, Object minVal, Object maxVal)
			throws ConstraintViolationException {

		if (minVal != null && maxVal != null) {
			int maxIdVal = (Integer) maxVal;
			if (maxIdVal > idCounter)
				idCounter = maxIdVal;
		}
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public Collection<Seafood> getSeafood() {
		return seafoods;
	}
	
	@DOpt(type = DOpt.Type.LinkAdderNew)
	public void setNewSeafood(Collection<Seafood> seafood) {
		this.seafoods = seafood;
		// do other updates here (if needed)
	}

	public void setSeafood(Collection<Seafood> seafood) {
		this.seafoods = seafood;
	}
	

	@Override
	public String toString() {
		return name;
	}
}